### ISSUE TITLE
end called before last item is processed

### ISSUE THREAD

**Issue by aaaristo** [andrewjstone/forkqueue#2]
https://github.com/andrewjstone/forkqueue/blob/master/queue.js#L72

can you change it to read:

  var remaining= this.queue.length;
  this.flush();

  if (!remaining && this.waiting.length == this.workers.length && this.done) {
    this.killWorkers();
    if (this.callback) this.callback();
  }

this way the end callback is called after the last item is processed. Otherwise the queue.length is 0 because the flush function has sent the last item but the worker still have to process it. Once it is processed the worker wil call next as usal and remaining will be 0.. 
Now the queue is correctly processed.

Thanks.

**Comment by andrewjstone** [comment]
It seems like you are correct. I'm testing the code right now.

**Comment by andrewjstone** [comment]
I added that code in. Thanks @aaaristo ! Great find!
